package com.gokhanaytekinn.sdandroid.ui.viewmodel

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.gokhanaytekinn.sdandroid.data.model.BillingCycle
import com.gokhanaytekinn.sdandroid.data.model.Subscription
import com.gokhanaytekinn.sdandroid.data.repository.SubscriptionRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.util.UUID

class AddSubscriptionViewModel(application: Application) : AndroidViewModel(application) {

    private val repository = SubscriptionRepository(application)

    private val _isLoading = MutableStateFlow(false)
    val isLoading: StateFlow<Boolean> = _isLoading.asStateFlow()

    private val _error = MutableStateFlow<String?>(null)
    val error: StateFlow<String?> = _error.asStateFlow()

    private val _isSuccess = MutableStateFlow(false)
    val isSuccess: StateFlow<Boolean> = _isSuccess.asStateFlow()
    
    // Form State
    private val _name = MutableStateFlow("")
    val name: StateFlow<String> = _name.asStateFlow()
    
    private val _amount = MutableStateFlow("")
    val amount: StateFlow<String> = _amount.asStateFlow()
    
    private val _currency = MutableStateFlow("TRY")
    val currency: StateFlow<String> = _currency.asStateFlow()
    
    private val _billingCycle = MutableStateFlow(BillingCycle.MONTHLY)
    val billingCycle: StateFlow<BillingCycle> = _billingCycle.asStateFlow()
    
    // YYYY-MM-DD
    private val _nextBillingDate = MutableStateFlow("")
    val nextBillingDate: StateFlow<String> = _nextBillingDate.asStateFlow()
    
    private val _isReminderEnabled = MutableStateFlow(false)
    val isReminderEnabled: StateFlow<Boolean> = _isReminderEnabled.asStateFlow()

    fun updateName(value: String) {
        _name.value = value
    }
    
    fun updateAmount(value: String) {
        _amount.value = value
    }
    
    fun updateCurrency(value: String) {
        _currency.value = value
    }
    
    fun updateBillingCycle(value: BillingCycle) {
        _billingCycle.value = value
    }
    
    fun updateNextBillingDate(value: String) {
        _nextBillingDate.value = value
    }
    
    fun updateIsReminderEnabled(value: Boolean) {
        _isReminderEnabled.value = value
    }

    fun saveSubscription() {
        if (_name.value.isBlank() || _amount.value.isBlank()) {
            _error.value = "Lütfen alanları doldurunuz."
            return
        }

        viewModelScope.launch {
            _isLoading.value = true
            _error.value = null
            
            try {
                // Determine category based on name (Simple logic for now)
                val category = determineCategory(_name.value)
                
                // Temp Subscription object to map to request in repository
                // ID is generated by backend usually, but for local object we might need one?
                // Repository uses Subscription object to create request.
                val subscription = Subscription(
                    id = UUID.randomUUID().toString(), // Helper ID, ignored by backend usually
                    name = _name.value,
                    cost = _amount.value.toDoubleOrNull() ?: 0.0,
                    currency = _currency.value,
                    billingCycle = _billingCycle.value,
                    nextBillingDate = _nextBillingDate.value.ifBlank { null },
                    category = category,
                    isActive = true
                )

                val result = repository.createSubscription(subscription)
                
                if (result.isSuccess) {
                    // TODO: Handle reminder creation if enabled
                    _isSuccess.value = true
                } else {
                    _error.value = result.exceptionOrNull()?.message ?: "Bir hata oluştu"
                }
            } catch (e: Exception) {
                _error.value = e.message
            } finally {
                _isLoading.value = false
            }
        }
    }
    
    private fun determineCategory(name: String): String {
        val lowerName = name.lowercase()
        return when {
            lowerName.contains("netflix") || lowerName.contains("disney") || lowerName.contains("prime") -> "Entertainment"
            lowerName.contains("spotify") || lowerName.contains("music") || lowerName.contains("apple music") -> "Music"
            lowerName.contains("adobe") || lowerName.contains("office") || lowerName.contains("microsoft") -> "Productivity"
            lowerName.contains("gym") || lowerName.contains("fitness") -> "Sports & Health"
            else -> "Other"
        }
    }
    
    fun resetState() {
        _isSuccess.value = false
        _error.value = null
        _name.value = ""
        _amount.value = ""
        _nextBillingDate.value = ""
    }
}
